// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuFtI-UxZqwL3bsCCC29sp2v80V_Dm_B4',
    appId: '1:452510999687:web:7d0ba21e8d388db62e8422',
    messagingSenderId: '452510999687',
    projectId: 'chat-app-32b56',
    authDomain: 'chat-app-32b56.firebaseapp.com',
    storageBucket: 'chat-app-32b56.appspot.com',
    measurementId: 'G-1DF0397QTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4z4EjXs_IOBKjHqGrKxp7bWpudzbreeM',
    appId: '1:452510999687:android:d33945215422f0982e8422',
    messagingSenderId: '452510999687',
    projectId: 'chat-app-32b56',
    storageBucket: 'chat-app-32b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx5fSU1RKjchF1oqhqGn1ubYPp_KQL4G8',
    appId: '1:452510999687:ios:aa561d48ab6f286a2e8422',
    messagingSenderId: '452510999687',
    projectId: 'chat-app-32b56',
    storageBucket: 'chat-app-32b56.appspot.com',
    iosClientId: '452510999687-vpsq2h5nmdfd7a4n8n9u0qcj2lel4ki1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx5fSU1RKjchF1oqhqGn1ubYPp_KQL4G8',
    appId: '1:452510999687:ios:aa561d48ab6f286a2e8422',
    messagingSenderId: '452510999687',
    projectId: 'chat-app-32b56',
    storageBucket: 'chat-app-32b56.appspot.com',
    iosClientId: '452510999687-vpsq2h5nmdfd7a4n8n9u0qcj2lel4ki1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuFtI-UxZqwL3bsCCC29sp2v80V_Dm_B4',
    appId: '1:452510999687:web:174abaa59ec666ce2e8422',
    messagingSenderId: '452510999687',
    projectId: 'chat-app-32b56',
    authDomain: 'chat-app-32b56.firebaseapp.com',
    storageBucket: 'chat-app-32b56.appspot.com',
    measurementId: 'G-GG6S1MCMZL',
  );
}
